services:
  mono:
    container_name: turret-mono
    network_mode: host

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      NODE_ENV: development

    volumes:
      - ./:/app
      - /run/user/1000/docker.sock:/var/run/docker.sock

    command: pnpm dev
    working_dir: /app

